"""Mock Coding Tool — creates files based on task description without AI.

For testing when Aider is not available.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
from dataclasses import dataclass

from app.shared import Health, ToolResult

logger = logging.getLogger(__name__)

DEFAULT_TIMEOUT = 30


@dataclass
class MockCodingTool:
    """Mock coding tool that creates files based on task description.

    Parses simple task descriptions like "Create hello.py with a hello world function"
    and creates the corresponding file.
    """

    name: str = "mock-coder"
    timeout: float = DEFAULT_TIMEOUT

    async def execute(
        self, task_description: str, workspace_path: str
    ) -> ToolResult:
        """Parse task description and create files.

        Supports patterns like:
        - "Create <file> with ..."
        - "Add <file> with ..."
        - "Write <file> with ..."

        Args:
            task_description: Natural language description of the coding task.
            workspace_path: Working directory for file operations.

        Returns:
            ToolResult with success status and output.
        """
        logger.info("Mock coding tool executing: %s", task_description)

        # Parse file name from task description
        # Match patterns like "Create X.py", "Add X.py", "Write X.py"
        patterns = [
            r"(?:create|add|write|make|generate|implement)\s+([^\s]+\.py)",
            r"(?:create|add|write|make|generate|implement)\s+a\s+file\s+([^\s]+\.py)",
            r"(?:file|source):\s*([^\s]+\.py)",
        ]

        filename = None
        for pattern in patterns:
            match = re.search(pattern, task_description.lower())
            if match:
                filename = match.group(1)
                break

        if not filename:
            # Try to extract any .py filename
            py_match = re.search(r"([a-zA-Z_][a-zA-Z0-9_]*\.py)", task_description)
            if py_match:
                filename = py_match.group(1)

        if not filename:
            return ToolResult(
                success=False,
                output="",
                error="Could not parse filename from task description",
            )

        # Ensure filename is safe
        filename = os.path.basename(filename)
        filepath = os.path.join(workspace_path, filename)

        # Generate content based on task description
        content = self._generate_content(task_description, filename)

        try:
            # Write the file
            with open(filepath, "w") as f:
                f.write(content)

            logger.info("Created %s with mock content", filepath)

            return ToolResult(
                success=True,
                output=f"Created {filename} with mock content:\n\n```python\n{content}```",
                error="",
            )
        except Exception as e:
            logger.exception("Failed to create %s", filepath)
            return ToolResult(
                success=False,
                output="",
                error=f"Failed to create file: {e}",
            )

    def _generate_content(self, task: str, filename: str) -> str:
        """Generate mock content based on task description."""
        task_lower = task.lower()

        # Hello world pattern
        if "hello" in task_lower or "world" in task_lower:
            if filename.startswith("test_") or "test" in task_lower:
                return '''"""Tests for hello module."""


def test_hello():
    """Test hello function."""
    from hello import hello
    assert hello() == "Hello World"


def test_hello_output(capsys):
    """Test hello output."""
    from hello import main
    main()
    captured = capsys.readouterr()
    assert "Hello World" in captured.out
'''
            return '''"""Hello module."""


def hello() -> str:
    """Return greeting message."""
    return "Hello World"


def main() -> None:
    """Print greeting."""
    print(hello())


if __name__ == "__main__":
    main()
'''

        # Function/docstring pattern
        func_match = re.search(r"function\s+(\w+)", task_lower)
        if func_match:
            func_name = func_match.group(1)
            return f'''"""{func_name} module."""


def {func_name}():
    """Function to implement."""
    pass


def main():
    {func_name}()


if __name__ == "__main__":
    main()
'''

        # Default: simple placeholder
        return f'''"""Generated by Forge mock coder."""


def main():
    """Main entry point."""
    pass


if __name__ == "__main__":
    main()
'''

    async def health_check(self) -> Health:
        """Return healthy status since this is a mock."""
        return Health(
            status="healthy",
            latency_ms=0,
            details={"tool": "mock-coder", "mode": "testing"},
        )
